### ISSUE TITLE
node-web-i2cでの動作確認

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/chirimen-drivers#22]
Node.js用のexampleを作成しnode-examplesフォルダに追加する。動作確認も。

- [x] @chirimen/ads1015@1.0.1-alpha.1 #8 にて対応
- [x] @chirimen/ads1x15@1.0.0-alpha.1
- [x] @chirimen/adt7410@1.0.1-alpha.0 #8 にて対応
- [x] @chirimen/ak8963@1.0.0-alpha.1
- [x] @chirimen/amg8833@1.0.0-alpha.1
- [ ] @chirimen/arduino-stepping-motor@1.0.0-alpha.1
- [x] @chirimen/bh1750@1.0.0-alpha.1
- [x] @chirimen/bme280@1.0.0-alpha.1
- [x] @chirimen/bmp180@1.0.0-alpha.1
- [x] @chirimen/bmp280@1.0.0-alpha.1
- [ ] @chirimen/canzasi@1.0.0-alpha.1
- [x] @chirimen/gp2y0e03@1.0.1-alpha.0  #8 にて対応
- [x] @chirimen/grove-accelerometer@1.0.0-alpha.1 #8 にて対応
- [x] @chirimen/grove-gesture@1.0.0-alpha.1 #8 にて対応
- [x] @chirimen/grove-light@1.0.0-alpha.4 #8 にて対応
- [x] @chirimen/grove-oled-display@1.0.0-alpha.1 #8 にて対応
- [x] @chirimen/grove-touch@1.0.0-alpha.1 #8 にて対応
- [x] @chirimen/ina219@1.0.0-alpha.1
- [x] @chirimen/mlx90614@1.0.0-alpha.1
- [x] @chirimen/mpu6050@1.0.0-alpha.1
- [x] @chirimen/mpu6500@1.0.0-alpha.1
- [x] @chirimen/neopixel-i2c@1.0.0-alpha.1
- [ ] @chirimen/pca9685-pwm@1.0.0-alpha.1
- [x] @chirimen/pca9685@1.0.1-alpha.0 #8 にて対応
- [x] @chirimen/pcf8591@1.0.0-alpha.1
- [x] @chirimen/s11059@1.0.2-alpha.0 #8 にて対応
- [x] @chirimen/sht30@1.0.0-alpha.1
- [x] @chirimen/tcs34725@1.0.0-alpha.1
- [x] @chirimen/veml6070@1.0.0-alpha.1 #8 にて対応
- [x] @chirimen/vl53l0x@1.0.3-alpha.0 #8 にて対応
- [x] @chirimen/vl53l1x@1.0.0-alpha.2

**Comment by kou029w** [comment]
動作確認していただいて問題無さそうなものはすべて正式にPublishしたのでクローズします
